project:
  type: website
  output-dir: docs  # Esto cambia _site por docs

website:
  title: "Juan Eguía Abad"
  navbar:
    right:
      - href: index.qmd
        icon: house
        text: Home
      - href: about.qmd
        icon: person
        text: About
      - text: "Proyectos"
        icon: cpu
        menu:
          - text: "📊 Marketing Bancario" # Nombre elegante en lugar del archivo
            href: final_project_bf_juan_eguia_v2.ipynb
          - text: "🏆 Histórico ganadores Grand Slams" # Añade una línea separadora si tienes varios
            href: https://www.youtube.com/watch?v=O4D2Vah2AWo

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



