project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - proyectos.qmd
    - proyectos/*.qmd
    - bank_marketing_pipe.ipynb
    # - dl_imagenes.ipynb   # descomenta/añade aquí el notebook de Deep Learning

website:
  title: "Juan Eguía Abad"
  navbar:
    right:
      - href: index.qmd
        icon: house
        text: Home
      - href: about.qmd
        icon: person
        text: About
      - href: proyectos.qmd
        icon: cpu
        text: Proyectos
    tools:
      - icon: github
        href: https://github.com/juan1639
      - icon: linkedin
        href: https://www.linkedin.com/in/juan-egu%C3%ADa-638878b7/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
